WebPyRobot/WebPyRobot/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'', include('backend.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^WebPyRobot/', include('backend.urls')),
]

WebPyRobot/backend/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import api_views
from . import views

app_name = 'backend'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup2/$', views.SignUp.as_view(), name='signUp2'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^registrationComplete/autoLogin/$', views.thanks, name='registrationComplete'),
    # url(r'^password_change$', views.password_change, name='password_change'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^battle/$', views.fight, name='fight'),
    url(r'^battle/(?P<player_pk>[0-9]+)/$', views.fight, name='fight'),
    url(r'^testcpu/$', views.versus, name='testcpu'),
    url(r'^versus/(?P<previous>[0-1])/$', views.versus, name='versus'),
    url(r'^versus/(?P<previous>[0-1])/(?P<player_pk>[0-9]+)/$', views.versus, name='versus'),
    url(r'^versus/(?P<previous>[0-1])/(?P<player_pk>[0-9]+)/(?P<script_pk>[0-9]+)/$', views.versus, name='versus'),
    url(r'^replay/$', views.replay, name='replay'),
    url(r'^editor/$', views.AIScriptView.as_view(), name='editor'),
    url(r'^editor/(?P<pk>[0-9]+)/$', views.editorDetail, name='editorDetail'),
    # url(r'^inventory/$', views.inventory, name='inventory'),
    # url(r'^market/$', views.market, name='market'),
    # url(r'^parameter/$', views.parameter, name='parameter'),
    # url(r'^agression/$', views.agression, name='agression'),
    # url(r'^changeStuff/$', views.changeStuff, name='changeStuff'),
    # url(r'^buyStuff/$', views.buyStuff, name='buyStuff'),
    url(r'^help/$', views.help, name='help'),
    url(r'^documentation/$', views.documentation, name='documentation'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^tutoriels/$', views.tutoriel, name='tutoriels'),
    # url(r'^recherche/$', views.recherche, name='recherche'),
    # url(r'^developpement/$', views.developpement, name='developpement'),
    url(r'^battle-histories/$', views.HistoriesView.as_view(), name="battle_histories"),
    url(r'^finish-battle/$', views.finish_battle, name='finish_battle'),
    url(r'^championnat/$', views.CreateChampionship.as_view(), name='championship'),
    url(r'^change_championship/$', views.change_championship, name='change_championship'),
    url(r'^profile/$', views.get_user_profile, name='profile_perso'),
    url(r'^training/$', views.select_player_for_training, name='select_player_for_training'),
    url(r'^championship/$', views.select_player_for_championship, name='select_player_for_championship'),
    url(r'^delete_script/$', views.delete_script, name='delete_script'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebPyRobot/backend/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm, forms.Form):
    username = forms.CharField(label='Pseudo', max_length=150, required=True, widget=forms.TextInput(attrs={'class':'validate', 'data-length':'150'}), help_text='Lettres, chiffres et @ . + - _ sont autorisés.')
    first_name = forms.CharField(label='Prénom',max_length=30, required=False)
    last_name = forms.CharField(label='Nom',max_length=30, required=False)
    # email = forms.EmailField(max_length=254,required=True, help_text='Requis. Renseignez une adresse valide.')
    email = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class':'validate'}), help_text='Renseignez une adresse valide.')
    password1 = forms.CharField(label='Mot de passe', required=True, widget=forms.PasswordInput, help_text="<ul>"
                                                                                                           "<li>Votre mot de passe ne peut pas être trop similaire à vos autres informations personnelles.</li>"
                                                                                                           "<li>Votre mot de passe doit contenir au moins 8 caractères.</li>"
                                                                                                           "<li>Votre mot de passe ne peut pas être un mot de passe couramment utilisé.</li>"
                                                                                                           "<li>Votre mot de passe ne peut pas être entièrement numérique.</li>"
                                                                                                           "</ul>")
    password2 = forms.CharField(label='Mot de passe (confirmation)', required=True, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class SignUpFormCustom (forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class':'validate'}))
    username = forms.CharField(label='Pseudo', required=True, widget=forms.TextInput(attrs={'class':'validate'}))
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput)
    # championnat = forms.ChoiceField(label='Championnat', required=True, widget=forms.Select())


class ChangeDataForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, disabled=True, widget=forms.TextInput(attrs={'class':'validate'}))
    username = forms.CharField(label='Pseudo', required=True, disabled=True, widget=forms.TextInput(attrs={'class':'validate'}))
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput)


class CodeForm (forms.Form):
    ia = forms.CharField(label='ia')


class ChampionshipForm(forms.Form):
    name = forms.CharField(label='Nom du championnat', max_length=60, required=True, widget=forms.TextInput(attrs={'class':'validate'}))
    secret_pass = forms.CharField(label='Code secret', max_length=60, required=False, widget=forms.TextInput(attrs={'type' : 'password'}), help_text='Créez un code secret.')

WebPyRobot/backend/views.py
import json
import random
from itertools import chain

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import logout as system_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.db.models import Q
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from channels import Group
from pure_pagination.mixins import PaginationMixin

from .constants import NotificationMessage
from .forms import SignUpForm, ChangeDataForm, CodeForm, ChampionshipForm
from .funct.funct import getItemByType, getBoolInventory
from .game.Game import Game
from .models import Weapon, Armor, Caterpillar, NavSystem, TypeItem, Inventory, DefaultIa
from .models import UserProfile, Tank, Ia, BattleHistory, Notification, FAQ, Championship
from .utils import validate_ai_script, award_battle_elo


def index(request):
    if request.user.is_authenticated:

        current_user = UserProfile.objects.get(user=request.user)

        battle = current_user.get_running_battle()

        champ_pk = UserProfile.objects.get(user=request.user).championship_set.all()[0].pk

        '''
        champ_pk = UserProfile.objects.get(user=request.user).championship_set.all()[0].pk
        print(champ_pk)

        players = Championship.objects.get(pk=champ_pk).players.all()
        for obj in players:
            print(obj.exp)

        champ = Championship.objects.all()
        for c in champ:
            print(c.name)
        '''

        # cpu_1 = UserProfile.objects.get(pk=1)
        # cpu_2 = UserProfile.objects.get(pk=2)
        # cpu_3= UserProfile.objects.get(pk=3)

        # print(cpu_1.pk, cpu_2.pk, cpu_3.pk)

        classement = Championship.objects.get(pk=champ_pk).players.all().order_by('-points')
        # classement = Championship.objects.get(pk=champ_pk).players.exclude(user=cpu_1.user).exclude(user=cpu_2.user).exclude(user=cpu_3.user).order_by('-exp')
        # print(classement)

        if not battle:
            context = {'money': UserProfile.objects.get(user=request.user).money,
                       'username': request.user,
                       'pageIn': 'accueil',
                       # 'point' : UserProfile.objects.get(user=request.user).exp,
                       'agression': UserProfile.objects.get(user=request.user).agression,
                       'tank': Tank.objects.get(owner=UserProfile.objects.get(user=request.user)),
                       'scripts': request.user.userprofile.ia_set.all(),
                       'active_script': request.user.userprofile.get_active_ai_script(),
                       'players': UserProfile.objects.exclude(pk=current_user.pk),
                       # 'classement' : UserProfile.objects.order_by('-exp'),
                       'classement': classement,
                       # 'all_championship': Championship.objects.all(),
                       'championnat': UserProfile.objects.get(user=request.user).championship_set.all()[0].name}
        else:
            context = {'money': UserProfile.objects.get(user=request.user).money,
                       'username': request.user,
                       'pageIn': 'accueil',
                       'inBattle': True ,
                       # 'point' : UserProfile.objects.get(user=request.user).exp,
                       'agression': UserProfile.objects.get(user=request.user).agression,
                       'tank': Tank.objects.get(owner=UserProfile.objects.get(user=request.user)),
                       'scripts': request.user.userprofile.ia_set.all(),
                       'active_script': request.user.userprofile.get_active_ai_script(),
                       'players': UserProfile.objects.exclude(pk=current_user.pk),
                       # 'classement' : UserProfile.objects.order_by('-exp'),
                       'classement': classement,
                       # 'all_championship': Championship.objects.all(),
                       'championnat': UserProfile.objects.get(user=request.user).championship_set.all()[0].name}

        return render(request, "backend/accueil.html", context)
    else:
        form = SignUpForm()
        context = {'form': form}
        return render(request, "backend/index.html", context)


@never_cache
def login(request):
    if request.user.is_authenticated:
        return redirect(reverse('backend:index'))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        from django.contrib.auth import authenticate
        user = authenticate(username=username, password=password)
        if user is not None:
            from django.contrib.auth import login
            login(request, user)
            urlnext = request.POST.get('next', reverse('backend:index'))
            return redirect(urlnext)
        else:
            form = SignUpForm()
            print("DEBUG: %s" % user)
            context = {
                'form': form,
                'next': request.GET.get('next'),
                'error': {'username': [{"code": "unique",
                                        "message": 'Votre Pseudo et/ou votre mot de passe ne correspond pas, veuillez réessayer. Merci'}]}
            }
            return render(request, 'backend/index.html', context)
    return render(request, 'backend/index.html', {'next': request.GET.get('next')})


@never_cache
def logout(request):
    system_logout(request)
    # context = {
    #     'error': {'username': [{"code": "unique",
    #                             "message": 'À bientôt sur PyRobot'}]}
    # }
    return redirect(reverse('backend:index'))
    # return render(request, 'backend/index.html', context)


def signup(request):
    context = {}
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')

            print(username, first_name, last_name, email)

            user = User.objects.get(username=username)

            # UserProfile(user=user, money=0, next_level_exp=int(1 / settings.EXP_CONSTANT), agression=True).save()
            UserProfile(user=user, points=0, coeff_K=40, nb_games=0, agression=True).save()


            # create ia file default
            userProfile = UserProfile.objects.get(user=user)
            i = Ia.objects.create(owner=userProfile,
                                  name="%s Default AI" % username,
                                  text=DefaultIa.objects.get(pk=1).text,
                                  active=True)

            Championship.objects.get(pk=2).add_user(userProfile)

            # default Inventory
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=1))
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=2))
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=3))
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=4))

            # init tank
            w = getItemByType(1, TypeItem(pk=1))
            a = getItemByType(1, TypeItem(pk=2))
            c = getItemByType(1, TypeItem(pk=3))
            n = getItemByType(1, TypeItem(pk=4))
            Tank.objects.create(owner=userProfile, ia=i, weapon=w, armor=a, caterpillar=c, navSystem=n)
            # raise Http404

            from django.contrib.auth import authenticate
            user = authenticate(username=username, password=raw_password)

            from django.contrib.auth import login
            login(request, user)
            return redirect('backend:login')
        else:
            # print(form.is_valid())
            # print(str(form.errors.as_data))
            context = {
                'form': form,
                'error': form.errors.as_json
            }
    else:
        form = SignUpForm()
        context = {
            'form': form,
            'error': 'ERROR METHOD POST'
        }
    return render(request, "backend/index.html", context)


class SignUp(FormView):
    template_name = 'backend/index.html'
    form_class = SignUpForm

    def get_success_url(self):
        self.success_url = reverse('backend:login')
        return super().get_success_url()

    def get(self, request, *args, **kwargs):
        from django.contrib.auth import logout
        logout(request)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        email = form.cleaned_data['email']
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            user = User.objects.create_user(username, email, password)

            # create User
            # UserProfile(user=user, money=0, next_level_exp=int(1 / settings.EXP_CONSTANT), agression=True).save()
            UserProfile(user=user, points=0, coeff_K=40, nb_games=0, agression=True).save()

            # create ia file default
            userProfile = UserProfile.objects.get(user=user)
            i = Ia.objects.create(owner=userProfile,

WebPyRobot/backend/templates/backend/ai_view.html
{% extends "base.html" %}
{% load static %}

{% block title %}PyRobot - AI Scripts {% endblock %}

{% block custom_css %}
 <!-- Editeur Python CSS -->
    <link rel="stylesheet" href="{% static 'codemirror/lib/codemirror.css' %}"/>
    <link rel="stylesheet" href="{% static 'codemirror/theme/cobalt.css' %}"/>
    <script src="{% static 'codemirror/lib/codemirror.js' %}"></script>


    <script src="{% static 'codemirror/mode/python/python.js' %}"></script>

    <script src="{% static 'codemirror/addon/edit/closebrackets.js' %}"></script>
    <script src="{% static 'codemirror/addon/edit/matchbrackets.js' %}"></script>

    <!-- CodeMirror Autocomplete-->

    <link rel="stylesheet" href="{% static 'codemirror/addon/hint/simple-hint.css' %}"/>
    <link rel="stylesheet" href="{% static 'codemirror/addon/hint/show-hint.css' %}"/>
    <script src="{% static 'codemirror/addon/hint/simple-hint.js' %}"></script>
    <script src="{% static 'codemirror/addon/hint/show-hint.js' %}"></script>
    <script src="{% static 'codemirror/addon/hint/python-hint.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row z-depth-1 section padding-section">
        <div class="pad row col s12 m12 l12 ">

            <div class="pad col s12 m3 l3 ">
                <ul class="collection with-header">
                    <li class="collection-header"><h4>Vos Scripts</h4></li>
                    <li class="collection-item">
                        <div>Code n°1<a href="#!" class="secondary-content"><i class="material-icons">send</i></a>
                        </div>
                    </li>
                    <li class="collection-item">
                        <div>Code n°2<a href="#!" class="secondary-content"><i class="material-icons">send</i></a>
                        </div>
                    </li>
                    <li class="collection-item">
                        <div>Code n°3<a href="#!" class="secondary-content"><i class="material-icons">send</i></a>
                        </div>
                    </li>
                </ul>
            </div>

            <div class="pad col s12 m9 l9 ">
                <nav>
                    <div class="nav-wrapper">
                        <a href="#" data-activates="mobile-demo" class="button-collapse"><i
                                class="material-icons">menu</i></a>
                        <ul class="left hide-on-med-and-down">
                            <li class="save"><a href="#">Sauvgarder</a></li>
                            <li><a href="{% url 'backend:fight' %}">Tester</a></li>
                        </ul>
                        <ul class="side-nav" id="mobile-demo">
                            <li class="save"><a class="waves-effect" href="#"><i
                                    class="material-icons left">save</i>Sauvgarder</a></li>
                            <li><a class="waves-effect" href="#"><i class="material-icons left">cached</i>Tester</a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <form id="code" action="{% url 'backend:editor' %}" method="post">
                    {% csrf_token %}
                    <textarea name="ia" id="ia" cols="40" rows="10">{{ code }}</textarea>
                    <p><strong>Note :</strong> Appuyez ' <i>Ctrl + Space</i> ' pour utliser l'autocomplétion
                        à tout moment.</p>
                    <p><strong>Attention :</strong> Remplacez ce qu'il y a entre trois quotes par une
                        valeur/variable qui correspond.</p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/editor.js' %}"></script>
{% endblock %}

WebPyRobot/backend/templates/backend/aide.html
{% extends "base.html" %}


{% block title %}WebPyRobot - Aide{% endblock %}

{% block content %}
  <div class="col s12 m9 l10 pad">
    <div class="row z-depth-1 section padding-section" >
      <div class="margTop col s12 m6 l6 center-align">
        <a class="waves-effect waves-light btn-large" href="{% url "backend:documentation" %}">Documentation</a>
      </div>
      <div class="margTop col s12 m6 l6 center-align ">
        <a class="waves-effect waves-light btn-large">Tutoriel</a>
      </div>

    </div>
  </div>
{% endblock %}

WebPyRobot/backend/templates/backend/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Bienvenue sur PyRobot</title>

    {% include 'backend/head.html' %}

    <style>
        body {
            background-color: #263238;
        }
    </style>


</head>
<body>

<nav class="indigo darken-4" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo yellow-text"
                                          onclick="window.location.href='/'">PyRobot</a>
        <ul class="right hide-on-med-and-down">
            <li><a class="modal-trigger yellow-text" href="#modalConnexion"><i class="fas fa-sign-in-alt fa-lg"></i>
                Connexion</a></li>
            <!--<li><a class="modal-trigger yellow-text" href="#modalInscription"><i class="fas fa-user-plus fa-lg"></i>
                Inscription</a></li>-->
        </ul>


        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
</nav>

<ul id="nav-mobile" class="side-nav">
    <li><a class="modal-trigger indigo-text darken-4" href="#modalConnexion"><i class="fas fa-sign-in-alt fa-lg"></i>
        Connexion</a></li>
    <li><a class="modal-trigger indigo-text darken-4" href="#modalInscription"><i class="fas fa-user-plus fa-lg"></i>
        Inscription</a></li>
</ul>


<!-- MODAL  -->
<div id="modalConnexion" class="modal">
    <div class="modal-content">
        <h4>Connexion</h4>
        <form method="post" action="{% url 'backend:login' %}">
            <div class="row">
                {% csrf_token %}
                <div class="input-field col s12">
                    <input placeholder="Player_1" id="username" name="username" type="text" class="validate">
                    <label for="first_name">Pseudo</label>
                </div>
                <div class="input-field col s12">
                    <input id="password" name="password" type="password" class="validate">
                    <label for="password">Mot de Passe</label>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="Se Connecter" class=" modal-action waves-effect indigo darken-4 btn">
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <p></p>
    </div>
</div>
<div id="modalInscription" class="modal">
    <div class="modal-content">
        <form action="{% url 'backend:signup' %}" method="post">
            {% csrf_token %}
            <h4>Inscription</h4>
            <div class="row">

                <!--{% for field in form %}
                  <div class="input-field col s12 m6 l6">
                    {{ field }}
                    <label for="{{ field.label }}">{{ field.label }}</label>
                    {% if field.help_text %}
                      <span>
                        {{ field.help_text | safe }}
                      </span>
                    {% endif %}
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  </div>
                {% endfor %}-->

                <div class="input-field col s12 m12 l12">
                    {{ form.username }}
                    <label for="{{ form.username.label }}">{{ form.username.label }}</label>
                    {% if form.username.help_text %}
                      <span>
                        {{ form.username.help_text | safe }}
                      </span>
                    {% endif %}
                </div>
                <div class="input-field col s12 m6 l6">
                    {{ form.first_name }}
                    <label for="{{ form.first_name.label }}">{{ form.first_name.label }}</label>
                    {% if form.first_name.help_text %}
                      <span>
                        {{ form.first_name.help_text | safe }}
                      </span>
                    {% endif %}
                </div>
                <div class="input-field col s12 m6 l6">
                    {{ form.last_name }}
                    <label for="{{ form.last_name.label }}">{{ form.last_name.label }}</label>
                    {% if form.last_name.help_text %}
                      <span>
                        {{ form.last_name.help_text | safe }}
                      </span>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l12">
                    {{ form.email }}
                    <label for="{{ form.email.label }}">{{ form.email.label }}</label>
                    {% if form.email.help_text %}
                      <span>
                        {{ form.email.help_text | safe }}
                      </span>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l12">
                    {{ form.password1 }}
                    <label for="{{ form.password1.label }}">{{ form.password1.label }}</label>
                </div>
                <div class="col s12 m12 l12">
                    {% if form.password1.help_text %}
                      <span>
                        {{ form.password1.help_text | safe }}
                      </span>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l12">
                    {{ form.password2 }}
                    <label for="{{ form.password2.label }}">{{ form.password2.label }}</label>
                    {% if form.password2.help_text %}
                      <span>
                        {{ form.password2.help_text | safe }}
                      </span>
                    {% endif %}
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" value="S'inscrire" class=" modal-action waves-effect indigo darken-4 btn">
            </div>
        </form>
    </div>
</div>

<div id="index-banner" class="parallax-container" style="height: 1000px; width: 100%;">
    <div class="section no-pad-bot">
        <div class="container">

            <h1 class="header center yellow-text bienvenue">Bienvenue sur PyRobot</h1>
            <br><br>
            <div class="section">
                <div class="row white-text lighten-5">
                     <div class="col s12 m12 l12">
                         <h5>
                            Sur notre site nous vous proposons de programmer, en langage Python,
                            le comportement d'un tank. Pour pimenter votre expérience, mesurez vous aux autres
                            utilisateurs de notre site et voyez le fruit de votre travail par le biais de
                            combats. Vos tanks seront placés dans une arène où se livrera un combat sans merci.
                        </h5>
                         <br><br>
                        <h5>
                            Le joueur qui aura programmé le meilleur tank gagnera la partie et
                            se verra octroyer des points de victoire le faisant monter au classement dans la ligue
                            choisie.<br><br>

                            La bataille est déjà lancée !!
                            <br><br>Que le meilleur programmeur gagne !!
                        </h5>
                         <br><br><br><br><br><br>
                     </div>
                    <div class="col s12 m12 l12 center-align">
                        <!--
                        <h5>
                            Envie d'apprendre un langage de programmation ? S'initier à la programmation ?
                            Vous êtes au bon endroit ! Pour vous, nous avons choisis la méthode d'apprentissage
                            par le jeu. Les jeux probots, crobots, etc, sont une manière ludique d'apprendre
                            un langage de programmation. Le langagege Python s'impose de plus en plus dans le
                            monde de l'éducation; pour apprendre aux novices les rudiments de la programmation.
                        </h5>
                        <br><br>
                        <h5>
                            Sur notre site nous vous proposons de programmer, dans ce langage,
                            le comportement d'un tank. Pour pimenter votre expérience, mesurez vous aux autres
                            utilisateurs de notre site et voyez le fruit de votre travail par le biais d'un
                            combat. Vos tanks seront placés dans une arène où se livrera un combat sans merci.
                        </h5>
                        <br><br>
                        <h5>
                            Le joueur qui aura programmé le meilleur tank gagnera la partie et
                            se verra octroyer des points de victoire le faisant monter au classement dans la ligue
                            choisie.
                            Un système de "Test" est disponible, si vous souhaitez vous mesurer à l'ordinateur
                            dont le niveau sera équivalent au vôtre.<br><br>

                            La bataille est déjà lancée !!
                            <br><br>Que le meilleur programmeur gagne !!
                        </h5>
                        -->

                        <a class="waves-effect indigo darken-4 waves-light btn-large modal-trigger yellow-text" href="#modalInscription"><i class="fas fa-play"></i> jouer</a>

                    </div>
                </div>
            </div>
        </div>
        <div class="parallax">
            <img src="{% static 'img/armour.png' %}" alt="Unsplashed background img 1">
        </div>
    </div>
</div>

{% include 'backend/footer.html' %}

</body>
<script>
    {% if error %}
        var errors = {{ error | safe }} ;
        msg_err = "" ;
        console.log(Object.keys(errors).length);
        var e;
        for (e in errors) {
            for(s in errors[e]){
                console.log(errors[e][s].message);
                msg_err += errors[e][s].message ;
                msg_err += "<br/><br/>";
            }
        }
        document.onload = setTimeout(function () {
            alertify.alert(msg_err);
        }, 1000);
    {% endif %}
</script>
</html>